config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jwc/', include('jwc.urls'))
]

jwc/urls.py
from django.urls import path
from . import views
import jwc


app_name  = 'jwc'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.index, name='index'),
    path('<int:q_id>/', views.detail, name='detail'),
    path('answer/create/<int:q_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('login/', views.login, name='login')

]

jwcadmin/jwcadmin/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

jwc/models.py
from django.db import models

# Create your models here.


#모델 : class단위
#django에서 지원하는 속성 Field 모음
#https://docs.djangoproject.com/en/3.0/ref/models/fields/#field-types
#모델이 새로 생성되면 migration 새로 해줘야함

class Question(models.Model):
    #제목처럼 글자수 제한 가능한 항목 : Charfield
    subject = models.CharField(max_length=200)
    #내용처럼 글자수 제한이 힘든 항목 : TextField
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    #ForeignKey : 기존 모델을 속성으로 연결
    #on_delete=models.CASCADE : 이 속성에 연결된 속성이 삭제되면 같이 삭제됨
    #foreign key 관련 내용 : https://jwccoding.tistory.com/24
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content

jwc/forms.py
from django import forms
from django.forms import fields, widgets
from jwc.models import Question


#django에는 두가지 form존재
#일반form과 모델form
#모델form은 모델과 연결된 form으로 저장하면 연결된 모델의 데이터를 저장 가능
#모델form 내부에 Meta클래스 필수
#Meta 클래스에는 사용할 모델과 모델의 속성 기입

#Questionform은 ModelForm을 상속받음
class Questionform(forms.ModelForm):
    class Meta:
        model = Question #사용할 모델
        fields = ['subject', 'content'] #Question form에서 사용할 Question 모델의 속성들
        #지정한 속성들의 모양 지정
        widgets = {
            'subject' : forms.TextInput(attrs={'class':'form-control'}),
            'content' : forms.Textarea(attrs={'class':'form-control', 'rows':10})
        }
        #지정한 속성들의 naming
        labels = {
            'subject' : '제목',
            'content' : '내용'
        }


#djangp form 더 알아보기
#https://docs.djangoproject.com/en/3.0/topics/forms/

jwc/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.http import HttpResponse
from .models import Question as Q
from .models import Answer as A
from .forms import Questionform
from django.core.paginator import Paginator

# Create your views here.

def home(request):
    return render(request,'jwc/home.html')


def index(request):
    '''
    jwc 질문 목록 출력

    '''
    #입력 파라미터
    #GET방식으로 호출된 URL에서 page값을 가져올 때 사용. default=1
    #예를 들어 .../jwc/?page=1
    page = request.GET.get('page','1')#페이지

    #질문 목록 출력 순서
    #기준이 되는 속성에 '-'를 붙이면 역순
    #조회
    question_list = Q.objects.order_by('-create_date')
    #페이징 처리
    paginator = Paginator(question_list,10) #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page) #페이지 객체 생성

    context = {'question_list':page_obj}

    return render(request, 'jwc/question_list.html',context)

def detail(request, q_id):
    '''
    jwc 질문의 답변 상세 페이지

    '''
    question = Q.objects.get(id=q_id)
    answer = A.objects.get(id=q_id)
    context = {'q':question, 'a':answer}
    return render(request,'jwc/question_detail.html',context)

def answer_create(request, q_id):
    '''
    jwc 질문 답변 등록

    '''
    question = get_object_or_404(Q,pk = q_id)
    #질문에 대한 답변 목록(answer_set) 생성(.create)
    #what is answer_set? auto created?
    #https://pybo.kr/pybo/question/detail/83/?page=1
    #django automatically created 'modelname(in small alphabet)+ _set' if connected with foreign key
    question.answer_set.create(content=request.POST.get('content'),create_date = timezone.now())

    #redirect : url 매핑
    #render : template 매핑
    return redirect('jwc:detail', q_id = q_id)




#POST방식 : HTML body에 전송해야할 데이터를 담아서 전달. 
#서버에게 동일한 요청을 전달해도 항상 응답이 다를 수 있음. 서버의 상태나 데이터를 변경시킬 때 사용

#GET방식 : 서버로부터 정보를 전달하기 위한 메소드. 요청을 전송할 때 HTML body에 담지 않고 url 끝에 쿼리스트링을 통해 전달.
#쿼리스트링이란 ?와 함께 이름과 값으로 쌍을 이루는 방식. ?...com/jwc/name1=value&name2=valu2...


def question_create(request):
    '''
    jwc질문 등록

    '''
    #form 변수에 Questionform 연결
    #request 인자에 들어오는 값(POST / GET)에 따라 구분
    if request.method == "POST":
        #응답 method가 POST방식이면 Questionform에 전달된 내용 및 데이터를 전달하여 form 변수에 저장
        #즉 사용자가 작성한 'subject'와 'content' 의 내용이 전달되어 form에 저장되어 객체로 생성
        #forms.py 의 Questionform 클래스에서 Question model의 subject와 content 를사용할 필드로 상속시켰기 때문
        form = Questionform(request.POST)
        #만약 입력에 있어서 유효하지 않다면, 즉 지정한 속서인 subject나 content 둘 중 하나라도 작성하지 않는다면 작동하지 않음
        if form.is_valid():
            #.save(commit=False) : save 함수의 선택적 인수로 commit = True와 False 사용 가능
            #False를 사용하면 DB에 즉시 저장 x, DB에 데이터를 저장하기 전에 특정 행위를 하고 싶을 때 사용
            question = form.save(commit=False)
            #이 때 임시저장 즉 commit=False를 하지 않으면 오류 발생. Question 모델의 속성인  create_date가 정의되지 않았기 때문
            #question = form.save()
            #create_date는 저장 시점에 생성되어야 하므로 Questionform의 속성으로 지정하지 않는다.
            question.create_date = timezone.now()
            question.save()
            return redirect("jwc:index")
    else:
        form = Questionform()
    context = {'form':form}
    return render(request, 'jwc/question_form.html', context)

def login(req):
    return render(req, 'jwc/login.html')





#html template 문법 사용
#https://wikidocs.net/70736

templates/base.html
<!-- template 상속용 기본 html 파일  -->
<!-- 사용법  -->
<!-- 1. 원하는 html파일들 생성  -->
<!-- 2. 상단에 해당 파일(base.html) 상속받기  -->

<!-- html파일 body 내에 작성할 내용들 작성  -->

<!-- css / link 등은 head에서 처리해야함  -->



{% load static %}

<html> 

<head>
    <!-- static내의 style.css파일 상속 -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- static내의 bootstrap.min.css 파일 상속 -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <title>JWC</title>

</head>

<body>
<!-- template들에게 상속될 부분 -->
{% include 'navbar.html' %}
{% block content%}


{% endblock %}
<!-- template들에게 상속될 부분 끝-->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>

<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>


</body>

</html>

templates/jwc/home.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">




<html>
    <title>
        JWC Application
    </title>
    <body>
        <div class="container row" style="float: none; margin:100 auto;"> <div class="col-md-3" style="float: none; margin:0 auto;">
            <h2>Welcome to JWC</h2>
            <h4>Let's use jwc</h4>
        </div>
        <div class="container row" style="float: none; margin:100 auto;"> <div class="col-md-3" style="float: none; margin:0 auto;">
            <form action="{% url 'jwc:index' %}" method = "post">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary btn-lg">go!</button>
            </form>
        </div>


    </body>


</html>

templates/jwc/login.html
{% extends 'base.html' %}
{% block content %}
<ul>
    <li onclick="kakaoLogin();">
    <a href="javascrpit:void(0)">
        <span>카카오 로그인</span>
    </a>
    </li>
    <li onclick="kakaoLogout();">
    <a href="javascrpit:void(0)">
        <span>카카오 로그아웃</span>
    </a>
    </li>
</ul>

<script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
<script>
Kakao.init('127b29e8d96ffa7a17e9425c460ffc45'); // 발급받은 키 중 javascript키를 사용
console.log(Kakao.isinitialized()); //sdk 초기화 여부 판단
//카카오 로그인
function kakaoLogin(){
    Kakao.Auth.login({
        success: function(response){
            Kakao.API.request({
                url:'/v2/user/me',
                success: function(response){
                    console.log(response)
                },
                fail: function(error){
                    console.log(error)
                },
            })
        },
        fail: function(error){
            console.log(error)
        },
    })
}
//z카카오 로그아웃
function kakaoLogout(){
    if(Kakao.Auth.getAccessToken()){
        Kakao.API.request({
            url: 'v1/user/unlink',
            success: function(response){
                console.log(response)
            },
            fail: function(error){
                console.log(error)
            },
        })
    Kakao.Auth.setAccessToken(undefined)
    }
}
</script>



{% endblock %}

templates/jwc/question_detail.html
{% extends 'base.html' %}
{% block content %}


<div class="container my-3">
    <h2 class="border-bottom py-2">{{ q.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ q.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ q.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{q.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in q.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ a.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'jwc:answer_create' q.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>


{% endblock %}

templates/jwc/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
    <h5 class="my -3 border bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
    {% csrf_token %}
    {{ form.as_ul }}
    <button type="submit">register</button>
    </form>
</div>


{% endblock %}

templates/jwc/question_list.html
{% extends 'base.html' %}
{% load jwc_filter %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'jwc:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
            {% endif %}
            </td>
            
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지-->
        {% if question_list.has_previous %}
        <li class ="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class = "page-item disabled">
            <a class = "page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지 리스트-->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!--다음페이지-->
        {% if question_list.has_next %}
         <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">    
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이지 처리 완료-->


    <a href = "{% url 'jwc:question_create' %}" class="btn btn-primary">질문 등록</a>
</div>

{% endblock %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'jwc:index' %}">JWC</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'jwc:login' %}">로그인</a>
            </li>
        </ul>
    </div>
</nav>